server:
  port: 8761

spring:
  application:
    name: discovery-server

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

# Eureka server setup (no self-registration)
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

